* JSON validation service
** What is this?
A RESTful service written in Scala; allows users to validate JSON documents against JSON schemas.  

** Technical architecture
The key part of the app is a Scalatra server. This receives POST and GET requests and processes them according to the following endpoints:
| Route                   | Purpose                                                                   |
|-------------------------+---------------------------------------------------------------------------|
| POST /schema/SCHEMAID   | Upload a JSON Schema with unique `SCHEMAID`                               |
| GET /schema/SCHEMAID    | Download a JSON Schema with unique `SCHEMAID`                             |
| POST /validate/SCHEMAID | Validate a JSON document against the JSON Schema identified by `SCHEMAID` |

The `JSONServlet` class handles incoming requests on the above routes, and passes them to the `JSONSchema` object.

The `JSONSchema` object has the following methods:

| Method   | Purpose                                              |
|----------+------------------------------------------------------|
| add      | Add a JSON Schema to the database if it is valid     |
| get      | Retrieve JSON Schema  from the database if it exists |
| validate | Validate a JSON Document against a JSON Schema       |

** Building and running
You'll need to set up the database. This should be a PostgreSQL database serving on the standard port (5432). Create a user jsonapp, and a database jsonapp owned by this user. Then run:
#+BEGIN_SRC sql
CREATE TABLE jsonschemas(schemaid varchar PRIMARY KEY, json varchar);
#+END_SRC
to create the table.

To run the app:
#+BEGIN_SRC sh
$ cd json-validation
$ sbt
> jetty:start
> browse
#+END_SRC

The app should be running on http://localhost:8080/. 
